services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    ports:
      - 3457:6379
    command: [ 'redis-server', '--appendonly', 'yes' ]       
    volumes:
      # Declare the volume
      - ./todo-backend/redis_data:/data

  backend:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    ports:
      - 3000:3000
      
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - redis
      - mongo
    container_name: todo-backend-prod

  app:
    image: todo-frontend-prod
      
    environment: 
      - REACT_APP_BACKEND_URL=http://localhost:8080/random/
      - WDS_SOCKET_PORT=0
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5001:80
    container_name: todo-frontend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend
  debug-helper:
    image: busybox
