version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blogs_database
    volumes:
      - ./blog-server/mongo_data:/data/db
    container_name: blogs-mongo-dev

  server:
    image: blogs-server-dev
    build:
      context: ./blog-client/
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-server/:/usr/src/app
    ports:
      - 3500:8080
    depends_on:
      - mongo
    container_name: blogs-server-dev

  app:
    image: blogs-client-dev
    build:
      context: ./blog-client/ 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./blog-client/:/usr/src/app
    ports:
      - 3000:3000
    container_name: blogs-client-dev
